### DISCUSSION TITLE
Can `could not find dependent assembly xunit.core` fail instead of skip?

### DISCUSSION THREAD

**Discussion by lawrence-laz** [xunit/xunit#2706] [Question] [answered]
I am running Xunit test project with the following versions:
```xml
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.msbuild" Version="2.4.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>

```
in Azure DevOps with the following config:
```yml
- task: VSTest@2
  displayName: Run Automated Tests
  inputs:
    testSelector: testAssemblies
    testAssemblyVer2: |
      **\*IntegrationTests.dll
      **\*UnitTests.dll
      !**\obj\**
    searchFolder: $(System.DefaultWorkingDirectory)
    runTestsInIsolation: true
    platform: ${{ parameters.buildPlatform }}
    otherConsoleOptions: '/Logger:trx /Enablecodecoverage'
```
We had a problem where this one test project was being skipped with the following message:
```
[xUnit.net 00:00:33.44] Skipping: ***.IntegrationTests (could not find dependent assembly 'xunit.core, Version=2.4.2')
```
I came across this by chance and have fixed the issue, but I would like for Xunit to fail the test run instead of skipping it, the next time this happens, so that I could be aware that part of the tests are no longer running in the pipeline.

Can this be configured somehow as it is? If not, could such setting be considered as an addition to Xunit?
