### DISCUSSION TITLE
Problem matching xUnit results in GitHub Actions

### DISCUSSION THREAD

**Discussion by KeithHenry** [xunit/xunit#2777] [Question] [answered]
I have also asked this [on Stackoverflow](https://stackoverflow.com/q/76884308/905) - it has a bounty of 500 if anyone wants SO rep.

I have a GitHub action that runs .NET xUnit tests (via the generic `dotnet test`):

```yaml
jobs:
  build-net:
    name: .NET build & test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.100      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build
```

This outputs that the tests have failed, but doesn't integrate them the way compiler errors are. Errors in `dotnet build` link to a line of code, errors in `dotnet test` xUnit output just get a single failed process message. 

I think I can fix that with a [problem matcher](https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md) - a JSON config file full of regexes that converts the text of xUnit failed test notifications to a format GitHub can associate with lines of code in the repo.

I've seen other action projects (such as [EnricoMi/publish-unit-test-result-action](https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#commit-and-pull-request-annotations)), but that achieves this with a Python script that also runs the rest of that action (which we don't want).

- Has anybody else done this with xUnit?
- Is there a problem matcher already written that could do this?
- Is there some option of xUnit for it to output test results in a GitHub compatible format without a matcher?
