### DISCUSSION TITLE
How to show `seed` value when running xUnit v3 tests with `Microsoft.Testing.Platform`

### DISCUSSION THREAD

**Discussion by filzrev** [xunit/xunit#3089] [Question] [answered]
When running xUnit v3 test with exe or `xUnit.net VSTest Adapter`
`seed` value can be confirmed by enabling `diagnosticMessages` options to `xunit.runner.json`.

But  when running tests with `Microsoft.Testing.Platform` by enabling `TestingPlatformDotnetTestSupport`.
`dotnet test` command don't show `seed` value.

Is there a way to show `seed` value when using `Microsoft.Testing.Platform`?
I've tried `dotnet test --tl:off -- --xunit-diagnostics on` command. But it's not works as expected.

**Comment by bradwilson** [comment, marked as answer]
There are two issues here.

The first is that you need to pass `--xunit-info` in Microsoft Testing Platform mode for us to show our headers and progress messages, and it's the headers that include the seed value.

The second is the same as [your other issue](https://github.com/xunit/xunit/issues/3092#issuecomment-2556234421) in that `dotnet test` is hiding our output by default.

For .NET 8 SDK: `dotnet test -p:TestingPlatformCaptureOutput=false -- --xunit-info --xunit-diagnostics on`

![image](https://github.com/user-attachments/assets/32f20e92-297d-407c-a949-1a5d077cb42e)

For .NET 9+ SDK, `dotnet test -- --xunit-info --xunit-diagnostics on` and then you must check the log file for the seed value.

![image](https://github.com/user-attachments/assets/43a9e611-cfaa-4f94-9cf7-e76750afe7dd)

**Comment by filzrev** [comment]
Thanks for providing detailed explanations.

Currently it seems difficult to output `seed` value on console logs when using .NET 9.
So I take another approach that **explicitly specify seed value** that described bellows.

**Background**
On my use case. 
I want to re-run tests **with same seed** when CI failed due to parallel execution problems.

But xUnit v3 determine seed value **when build assemblies**.
https://github.com/xunit/xunit/blob/2c69b26a21f3b06c2619bed13000b1b9e7abe595/src/xunit.v3.core/Framework/TestFrameworkExecutor.cs#L70-L71

So it need to output seed value to logs to use same seed on CI.

**Another Approach: Explicitly set fixed seed value**
When running tests on GitHub Actions environment.
It can use [`github.run_number`](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs) context value that is incremented by 1. 
And this value is not changed when re-run workflow.

So it can use as fixed seed value.

**Example workflow**
```
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      seed:
        description: 'Enter an integer value between 0 and 2147483647.'
        type: number
        required: true
        default: 0

env:
  seed: ${{ inputs.seed || github.run_number }}

jobs:
  test:
    (...)
    steps:
      (...)
    - run: dotnet test -c Release -- --seed ${{ env.seed }}
```
