### ISSUE TITLE
GitHub Actions tests fail when --no-build is present

### ISSUE THREAD

**Issue by ThorANilsson** [xunit/xunit#3297]
Hi there,

We're trying to use a GitHub Actions workflow for build and running some unit tests. We have encountered an error that always seems to occur for us when running the unit tests if the flag `--no-build` flag is present on the `dotnet test` command. We really want the `--no-build` when running the tests as it's a big waste of time and resources to re-build the project to run the unit tests.

This is the test job that fails:
```
test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Run tests
        run: dotnet test Backend.Tests/Backend.Tests.csproj --no-build --verbosity normal
```

The error:
```
Build started 05/15/2025 08:44:28.
Test run for /home/runner/work/projectname/projectname/Backend.Tests/bin/Release/net8.0/Backend.Tests.dll (.NETCoreApp,Version=v8.0)
VSTest version 1[7](https://github.com/projectname).11.1 (x64)

The argument /home/runner/work/projectname/projectname/Backend.Tests/bin/Release/net8.0/Backend.Tests.dll is invalid. Please use the /help option to check the list of valid arguments.
     1>Project "/home/runner/work/projectname/projectname/Backend.Tests/Backend.Tests.csproj" on node 1 (VSTest target(s)).
     1>_VSTestConsole:
         MSB41[8](https://github.com/projectname/actions/runs/15040589421/job/42271176517#step:4:9)1: The "VSTestTask" task returned false but did not log an error.
     1>Done Building Project "/home/runner/work/projectname/projectname/Backend.Tests/Backend.Tests.csproj" (VSTest target(s)) -- FAILED.
```

We tried using the `--configuration Release` flag but error persists. Only thing that makes the unit tests run is removing `--no-build`. Thanks in advance for any input on this issue! 😊

**Comment by ThorANilsson** [comment]
Works when putting the build and test in the same job:

```
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore Backend/Backend.sln

      - name: Build
        run: dotnet build Backend/Backend.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test Backend.Tests/Backend.Tests.csproj --configuration Release --no-build --verbosity normal
```
