### ISSUE TITLE
Not able to exit the code after successfully run the test case

### ISSUE THREAD

**Issue by francisdurairaj** [xunit/xunit#612]
I am trying to publish the asp.net vNext project via travis CI where the yml file is as given below.
Where the solution is build properly and after running the test case it waiting for the user input i guess.
Kindly help is resolving the same.

```
language: CSharp
mono:
  - latest
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade
  - dnu restore
script:
  - cd src/Sample/  && dnu build
  - cd - && cd src/Sample.XUnit/ && dnu restore
  - dnx test
deploy:
     edge: true
     provider: cloudfoundry
     username: myemailid@yahoo.co.in
     password: *******
     api: https://api.run.pivotal.io
     organization: mysampleorg
     space: development
```

Travis stuck at this line as given below
```
=== TEST EXECUTION SUMMARY ===
   MyFirstDnxUnitTests  Total: 5, Errors: 0, Failed: 0, Skipped: 0, Time: 0.176s
```
